### ISSUE TITLE
Inaccuracy in the Readme

### ISSUE THREAD

**Issue by pmaxtim** [aws-samples/eks-alb-istio-with-tls#5]
For "Install and configure Istio" part, where we need to label dafault namespace, we have
`kubectl label default ns istio-injection=enabled --overwrite`
but it causes an error:
`error: the server doesn't have a resource type "default"`

there shoul be:
`kubectl label ns default istio-injection=enabled --overwrite`

**Comment by saleem-mirza** [comment]
Thank you @pmaxtim for highlighting it. There was a pending PR and now issue is fixed. However, your contribution is highly appreciated.
